# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15bb4b19b6b3c29a68421592bfa0ee6bfa5f2bb47accb7869148913e3aa533a397a813e932e7c7c25886a4daacf181bb4d2bca1d1d7f699a9cf8f9ca9327e0eb

test:
  secret_key_base: bc4141d2128a09f42b1382e00572db591f6bbb50ae217724adc3bb6f69f1f8950c53f749c4e79ff029f62f7d58d263818f58794465514b0bcc6164b98e7ffa1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
